version: 1

formatters:
    simple:
        format: "%(levelname)s %(name)s#%(lineno)d: %(message)s"

    complex:
        format: "%(asctime)s %(levelname)s %(name)s#%(lineno)d: %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple

    file:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        backupCount: 1
        level: DEBUG
        formatter: complex
        filename : log/yamlquotes.log

loggers:
    yamlquotes:   
        level: DEBUG
        handlers: [console,file]
        propagate: yes
